# Generated by Django 5.2.9 on 2025-12-23 17:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('conversations', '0002_conversationmemory'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='conversationmemory',
            name='summary',
        ),
        migrations.AddField(
            model_name='conversationmemory',
            name='memory',
            field=models.JSONField(default=dict),
        ),
    ]
